[package]
name = "client_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "*"
prost = "0.14"
tonic-prost = "*"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread","io-std"] }
tokio-stream = "*"

[build-dependencies]
tonic-prost-build = "*"
